# Site settings
title: Shashi's Blog
header-img: img/home-bg.jpg
email: shashi.dokania@gmail.com
description: "Full Stack Software Engineer"
baseurl: ""
url: "http://shashi-dokania.github.io"
twitter_username: sdokania
github_username:  shashi-dokania
facebook_username:  shashi.d.prasad

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
